spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
        filters:
          - StripPrefix=2
      - id: servicio-item
        uri: lb://servicio-item
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2